import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { init, useConnectWallet } from "@web3-onboard/react";
import injected from "@web3-onboard/injected-wallets";

init({
  wallets: [injected()],
  chains: [
    {
      id: "0x1",
      token: "ETH",
      label: "Ethereum Mainnet",
      rpcUrl: "https://mainnet.infura.io/v3/eb347fc6f4b84938bf8b111cc08a4814",
    },
  ],
});

export default function Home() {
  const [{ wallet, connecting }, connect, disconnect] = useConnectWallet();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => connect()}>Connect</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
